# A sample Gemfile
source 'https://rubygems.org'

#group :development, :test do
 # gem 'rspec-rails', '< 3.0.0'
#end

gem 'ssh-exec'

gem 'rspec', group: [:test, :development]
group :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'nokogiri'
end



